Fix SPARQL unicode names support (fix #1653)
rouge-ruby/rouge pull request #1654
Opened 2020-12-21 08:35 UTC by jakubklimek

Fix for #1653

2022-01-25 23:26 UTC, tancnle requested changes
Thank you for your contribution @jakubklimek ❤️. The PR looks good overall 👍🏼 I have left a small suggestion for your consideration. Please let me know what you think 🙏🏼

2022-01-25 23:26 UTC, tancnle commented on lib/rouge/lexers/sparql.rb
> +        rule %r((([[:word:]]|[_-])*)(:)(([[:word:]]|[_-])+)?) do |m|
**suggestion:** We can simplify this regex a bit more. 

- There seems to be some unexpected capture groups 
  ```rb
  [2] pry(main)> "podmínky-užití:databáze-chráněná-zvláštními-právy".scan(regex)
  => [["podmínky-užití", "í", ":", "databáze-chráněná-zvláštními-právy", "y"]]
  ```
- `[:word:]` also matches punctuation including underscore `_` 

```suggestion
        rule %r(([[:word:]-]*)(:)([[:word:]-]+)?) do |m|
```

And that means we end up with exactly 3 capture groups and can adjust the matches accordingly. What do you think?

2022-01-26 05:42 UTC, tancnle commented on lib/rouge/lexers/sparql.rb
> +          token Str::Symbol, m[4]
I think we would want to update the indices.

```suggestion
          token Operator, m[2]
          token Str::Symbol, m[3]
```

2022-01-26 05:58 UTC, tancnle commented
Thank you @jakubklimek. Let's merge 🚀

2022-01-26 05:58 UTC, merged

2022-01-26 06:10 UTC, jakubklimek commented
@tancnle Thank you!